const constants = {
    CHANGE_TOKEN: "CHANGE_TOKEN",
    CHANGE_CHECKED: "CHANGE_CHECKED",
    REQUESTED: "REQUESTED",
    CHANGE_LOGIN: "CHANGE_LOGIN",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    ADD_ARRAY: "ADD_ARRAY",
    ADD_TODO: "ADD_TODO",
    CHANGE_ID: "CHANGE_ID",
    CHANGE_ARRAY: "CHANGE_ARRAY",
    EDIT_ARRAY: "EDIT_ARRAY",
    REMOVE_CASE: "REMOVE_CASE",
    REQUEST_CHANGEDATA: "REQUEST_CHANGEDATA",
    REQUEST_ADDTODO: "REQUEST_ADDTODO",
    CHECK_TODO: "CHECK_TODO"
}
export default constants